fix: add favicons
pactus-project/PIPs pull request #160
Opened 2024-07-10 05:37 UTC by Ja7ad

2024-07-10 18:32 UTC, b00f requested changes
Why don't use PIP icon:

https://github.com/pactus-project/PIPs/blob/main/assets/readme/pip.png

2024-07-10 18:32 UTC, b00f commented on .gitignore
> +Gemfile.lock
Let's keep `Gemfile.lock` as the version in GitHub Actions changes, and we may fail to compile the website.

2024-07-10 18:32 UTC, b00f commented on assets/favicons/site.webmanifest
> +    "name": "",
`safari-pinned-tab` is not same as other icons.

2024-07-10 19:09 UTC, Ja7ad commented
@b00f Done

2024-07-11 08:48 UTC, b00f approved these changes

2024-07-11 09:12 UTC, merged