pip-29: Draft Batch Transactions
pactus-project/PIPs pull request #169
Opened 2024-08-05 11:46 UTC by maxipaz

Draft for a new PIP to define `Batch Transactions` in Pactus.

Should be discussed and get completed.

2024-08-05 13:07 UTC, b00f requested changes
@maxipaz Overall, it looks good. We can add it to the PIPs and start discussing it.

2024-08-05 13:07 UTC, b00f commented on PIPs/pip-29.md
> +## Pros
We don't have this title (Header-2) in PIP-templates. 
Let's keep it consistent with others. You can check the PIP template here: [PIP Template](https://github.com/pactus-project/PIPs/blob/main/pip-template.md?plain=1)

2024-08-05 13:07 UTC, b00f commented on PIPs/pip-29.md
> +## Conclusion
This title also not available in PIP-template.

2024-08-10 09:12 UTC, Ja7ad commented
@maxipaz Please fix request changes before merge.

2024-08-11 07:21 UTC, merged