Added PIP22 to resolve client agent pattern in GUI for windows
pactus-project/PIPs pull request #91
Opened 2024-01-29 14:03 UTC by nagarajmanjunath

When opening a pull request to submit a new PIP, please use the suggested template: https://github.com/pactus-project/PIPs/blob/master/pip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2024-01-29 14:29 UTC, kehiy commented
@pactus-project/research @nagarajmanjunath 

Most of the time an improvement proposal (especially for blockchain and network protocols) aims to be a general proposal for all implementations and clients. as I can see this proposal is only useful for our current GUI implementation on pactus-go core.

What do you think?

2024-01-30 05:40 UTC, Ja7ad approved these changes

2024-01-30 05:40 UTC, Ja7ad commented on PIPs/pip-22.md
> +category: core
Better change category to `Interface`

2024-01-30 05:40 UTC, Ja7ad commented on PIPs/pip-22.md
> +---
If this proposal it is related to another proposal add header:

```
requires: 14
```

2024-01-30 05:42 UTC, Ja7ad requested changes
Please changes before merge!!!

2024-01-31 06:27 UTC, Ja7ad approved these changes

2024-01-31 06:27 UTC, merged